ALTER TABLE TRAJET DROP FOREIGN KEY FK_TRAJET_VOITURE_IDVOITURE
ALTER TABLE TRAJET DROP FOREIGN KEY FK_TRAJET_DEPART_IDPOSITION
ALTER TABLE TRAJET DROP FOREIGN KEY FK_TRAJET_CONDUCTEUR_IDUSER
ALTER TABLE TRAJET DROP FOREIGN KEY FK_TRAJET_ARRIVEE_IDPOSITION
ALTER TABLE USER DROP FOREIGN KEY FK_USER_POSITION_IDPOSITION
ALTER TABLE TRAJET_USER DROP FOREIGN KEY FK_TRAJET_USER_passagers_IDUSER
ALTER TABLE TRAJET_USER DROP FOREIGN KEY FK_TRAJET_USER_Trajet_IDTRAJET
ALTER TABLE TRAJET_POSITION DROP FOREIGN KEY FK_TRAJET_POSITION_Trajet_IDTRAJET
ALTER TABLE TRAJET_POSITION DROP FOREIGN KEY FK_TRAJET_POSITION_points_IDPOSITION
DROP TABLE POSITION
DROP TABLE TRAJET
DROP TABLE USER
DROP TABLE VOITURE
DROP TABLE TRAJET_USER
DROP TABLE TRAJET_POSITION
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
